### PR TITLE
feat: added rating

### PR DESCRIPTION
**Pull request by bhavyaj12**
- I've added the normal read only rating, dynamic rating with JS I will add later
- Toast is an optional one for me, so will add later if time permits in the same branch and merge 
- For now please review rating so I can merge

image

### CODE REVIEW

**Review by bmendhe23 — APPROVED** [review]
Looks good to merge.

**Review by Pratham82 — COMMENTED** [review]
Good to go

**Review by sashaboi — APPROVED** [review]
Looks good ! ( side note : a nice padding left 10px to your left sidebar might look a little more aesthetic ?)
Good to go !
Onkar Deshpande

**Comment by bhavyaj12** [comment]
> Looks good ! ( side note : a nice padding left 10px to your left sidebar might look a little more aesthetic ?) Good to go ! Onkar Deshpande

Yes I will add it at the end as a fix

**Pull request merged**
