### PR TITLE
feat: added modal

### PR DESCRIPTION
**Pull request by bhavyaj12**
Added the following: 

- Modal
- Preview: https://deploy-preview-14--halcyon-ui.netlify.app/pages/components/modal

modal

### CODE REVIEW

**Review by harshitpaliwal95 — APPROVED** [review]
- looks good

**Review by Balakumar3018 — APPROVED** [review]
Good to go

**Comment by SuchitaGhadge** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/bhavyaj12/reviewers)

**Comment by SuchitaGhadge** [comment]
looks good to merge

**Pull request merged**
