### PR TITLE
feat: added alert and buttons

### PR DESCRIPTION
**Pull request by bhavyaj12**
### Added Alerts and Buttons

- Differet variants of alerts
- Different variants of buttons
- Modified the links of nav as well as some fixes

### CODE REVIEW

**Comment by anurag-kkumarr** [comment]
Looks good to merge it.

**Review by vikrantkode — COMMENTED** [review]
Looks good to me.

**Review by bmendhe23 — APPROVED** [review]
Looks good to me @bhavyaj12 .

**Comment by jatinmore** [comment]
-Iframe i guess getting outside your main content div 
-UI looks good
-alert button components are good

**Pull request merged**
