### PR TITLE
feat: added grid

### PR DESCRIPTION
**Pull request by bhavyaj12**
Added the following

- 2 col grid
- 3 col grid
- Preview: https://deploy-preview-16--halcyon-ui.netlify.app/pages/components/grid

grid

### CODE REVIEW

**Review by harshitpaliwal95 — APPROVED** [review]
- looks good to me 
- clean ui

**Review by kr-sarvesh — COMMENTED** [review]
responsive UI, good to go.

**Review by Balakumar3018 — APPROVED** [review]
good to go. remove extra space between lines

**Comment by TJain02** [comment]
The code is clean. The UI is also clean. Looks good to me.

**Pull request merged**
